project:
  type: book
  output-dir: docs
  resources:
    - CNAME
    - .nojekyll

execute:
  cache: true
  freeze: auto

book:
  title: "Cards & Stories"
  author: "Rohit Farmer"
  date: today
  site-url: https://cardsandstories.rohitfarmer.com
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: false
  sidebar:
    style: "floating"
  page-footer:
    left: |
      Cards & Stories was written by Rohit Farmer.
    right: |
      © 2025 Rohit Farmer · <a href="license.html">License</a> ·
      <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>
  
  cover-image: images/cover.webp
  cover-image-alt: |
    Book cover with fronts and backs of selected postcards placed in a grid. 
  favicon: images/cover.webp

  twitter-card: true
  open-graph: 
    description: "An elegant, image-rich postcard book—stories from friends and from Rohit's own wanderings."
  
  chapters:
    - index.qmd
    - license/index.qmd
    - dedication/index.qmd
    - introduction/index.qmd
    - part: parts/favorites/index.qmd
      chapters:
        - parts/favorites/outposts-of-the-world/index.qmd
        - parts/favorites/beyond-paper/index.qmd
        - parts/favorites/vintage-voices/index.qmd
        - parts/favorites/the-language-of-stamps/index.qmd
    - part: parts/sent-by-friends/index.qmd
      chapters:
        - parts/sent-by-friends/croatia/index.qmd
        - parts/sent-by-friends/ireland/index.qmd
        - parts/sent-by-friends/italy/index.qmd
        - parts/sent-by-friends/morocco/index.qmd
        - parts/sent-by-friends/uk/index.qmd
        - parts/sent-by-friends/usa/index.qmd
    - part: parts/collected-along-the-way/index.qmd
      chapters:
        - parts/collected-along-the-way/campuses-institutions/index.qmd
        - parts/collected-along-the-way/museums/index.qmd
        - parts/collected-along-the-way/outdoors/index.qmd
    - part: parts/from-the-postcard-community/index.qmd
      chapters:
        - parts/from-the-postcard-community/architecture-and-cityscapes/index.qmd
        - parts/from-the-postcard-community/art-and-design/index.qmd
        - parts/from-the-postcard-community/nature-and-landscapes/index.qmd
        - parts/from-the-postcard-community/wildlife-and-animals/index.qmd
    - epilog/index.qmd

format:
  html:
    include-in-header:
      - text: |
          <meta name="robots" content="noindex">
          <script defer src="https://cloud.umami.is/script.js" data-website-id="eff73109-3747-4a41-9e1f-976cec4e874b"></script>
    theme:
      - litera
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.5
    toc: false
    number-sections: false
    lightbox: true
    link-external-newwindow: true
    link-external-icon: true
    
editor: source
